import { Users, Gamepad2, BarChart3, BookOpen, Lightbulb, Zap } from "lucide-react";

// Component: Features Section
const FeaturesSection = () => {
    const features = [
      {
        icon: <Users className="h-10 w-10 text-blue-500" />,
        title: 'Personalized Learning Paths',
        description: 'Our AI adapts the game difficulty and content to your individual pace and learning style.',
      },
      {
        icon: <Gamepad2 className="h-10 w-10 text-blue-500" />,
        title: 'Interactive Gamification',
        description: 'Engage with tasks, challenges, leaderboards, and rewards that make learning addictive.',
      },
      {
        icon: <BarChart3 className="h-10 w-10 text-blue-500" />,
        title: 'Trackable Progress',
        description: 'Visualize your growth with detailed analytics and see how far you’ve come.',
      },
      {
        icon: <BookOpen className="h-10 w-10 text-blue-500" />,
        title: 'Diverse Skill Library',
        description: 'Access a growing catalog of skills across various domains, from technical to creative.',
      },
       {
        icon: <Lightbulb className="h-10 w-10 text-blue-500" />,
        title: 'AI-Driven Content',
        description: 'Learning scenarios and challenges are dynamically generated by AI, ensuring fresh and relevant content.',
      },
      {
        icon: <Zap className="h-10 w-10 text-blue-500" />,
        title: 'Rapid Skill Acquisition',
        description: 'Learn complex topics faster through immersive, game-based practical application.',
      },
    ];
  
    return (
      <section id="features" className="py-16 sm:py-24 bg-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">Why Choose MENTOR AI?</h2>
            <p className="mt-4 text-lg text-gray-400 max-w-2xl mx-auto">
              Discover the features that make MENTOR AI the future of learning.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-gray-800 p-6 rounded-xl shadow-md hover:shadow-blue-500/20 transition-shadow duration-300">
                <div className="flex items-center mb-4">
                  {feature.icon}
                  <h3 className="ml-4 text-lg font-semibold">{feature.title}</h3>
                </div>
                <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  };

  export default FeaturesSection;